# Generated by Django 5.1.6 on 2025-03-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='strength',
            field=models.IntegerField(default=0, editable=False, verbose_name='Сила'),
        ),
    ]
