# Generated by Django 5.1.6 on 2025-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='strength',
            field=models.IntegerField(default=0, verbose_name='Сила'),
        ),
    ]
